version: 1
update_configs:
  - package_manager: "python"
    directory: "/src"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          update_type: "all"
  - package_manager: "python"
    directory: "/k8s"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          update_type: "all"
